backend:
  name: gitlab
  repo: northside-systems/testing-netlify-cms
  auth_type: implicit
  app_id: b763f33ddfc81e5202eeadc7c14b2b593df1f00860564fa6e0ddfb541c2e270b

local_backend: true
media_folder: static/media
public_folder: /media
publish_mode: editorial_workflow
display_url: https://northsidesystems.com
logo_url: https://dev.northsidesystems.com/images/logo.svg

collections:
  - name: 'navigation'
    label: 'Navigation'
    label_singular: 'Navigation Link'
    folder: 'content/navigation'
    create: true
    slug: '{{slug}}'
    summary: '{{order}} - {{title}}'
    editor:
      preview: false
    sortable_fields: ['order','title']
    fields:
      - { label: 'Link Text', name: 'title', widget: 'string' }
      - { label: 'Order', name: 'order', widget: 'number' }
      - label: 'Page'
        name: 'page'
        widget: 'relation'
        collection: 'pages'
        value_field: '{{slug}}'
        search_fields: ['title','description']
        display_fields: ['{{title}} (/{{slug}})']

  - name: 'pages'
    label: 'Pages'
    label_singular: 'Page'
    folder: 'content/pages'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Settings'
    delete: false # Prevent users from deleting documents in this collection
    editor:
      preview: false
    files:
      - file: 'content/settings/global.yml'
        label: 'Global Settings'
        name: 'global-settings'
        fields:
          - { label: Site Title, name: siteTitle, widget: string }
          - { label: Site Url, name: siteUrl, widget: string, required: false }
          - {
              label: Site Description,
              name: siteDescription,
              widget: text,
              required: false,
            }
          - label: Social Media Card
            name: socialMediaCard
            widget: object
            fields:
              - { label: Image, name: image, widget: image, required: false }
          - {
              label: Google Analytics Tracking Id,
              name: googleTrackingId,
              widget: string,
              required: false,
            }
      - file: 'content/settings/hero.yml'
        label: 'Hero Rotating Items'
        name: 'hero-items'
        fields:
          - label: Items
            name: items
            widget: list
            summary: '{{fields.text}}'
            collapsed: true
            field: { label: Text, name: text, widget: string }
